packages:
  - "."
  
catalog: {}

# Minimum release age of dependencies to prevent supply chain attacks (7 days)
minimumReleaseAge: 10080

# Prevent tampering of lockfile and enforcing signatures
trustPolicy:
  no-downgrade: true
